services:
  db:
    image: postgres:15
    container_name: booknest_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: booknest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    image: booknest-backend:4.0
    container_name: booknest_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
